1234

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,8 +1,27 @@
-#!/usr/bin/env bash
-# installs nginx and configure it to listen on port 80
-# print "Hello World"
+#!/bin/bash
 
-sudo apt-get update
-sudo apt-get -y install nginx
-echo 'Hello World!' | sudo tee /var/www/html/index.html
-service nginx start
+# Check if all 4 parameters are provided
+if [ "$#" -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
+
+# Disable strict host key checking
+export SSH_OPTIONS="-o StrictHostKeyChecking=no"
+
+# Transfer the file using scp
+scp $SSH_OPTIONS -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/
+
+# Check scp exit status
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully."
+else
+    echo "Error transferring file."
+fi
+
